# Generated by Django 5.2.1 on 2025-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
