# Generated by Django 5.2.1 on 2025-08-14 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_habit_created_at_alter_habitrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
