# Generated by Django 5.2.1 on 2025-09-17 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_habitrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
